source 'https://github.com/CocoaPods/Specs.git'

target 'palplus-sdk-ios', :exclusive => true do
   pod "AFNetworking", "~> 2.0"
   pod "palplus-sdk-ios", :git => "https://github.com/palplus-api/palplus-sdk-ios.git", :tag => '0.1.2'
  #pod "palplus-sdk-ios", :path => "../"
end

target 'Tests', :exclusive => true do
   pod "AFNetworking", "~> 2.0"
   pod "palplus-sdk-ios", :git => "https://github.com/palplus-api/palplus-sdk-ios.git", :tag => '0.1.2'
  #pod "palplus-sdk-ios", :path => "../"
end

