source 'https://github.com/CocoaPods/Specs.git'

target 'palplus-sdk-ios', :exclusive => true do
  pod "palplus-sdk-ios", :git => "https://github.com/palplus-api/palplus-sdk-ios.git"
end

target 'Tests', :exclusive => true do
  pod "palplus-sdk-ios", :git => "https://github.com/palplus-api/palplus-sdk-ios.git"
end

